LibraryManagementSystem/LibraryManagementSystem/Controllers/AuthorsController.cs
using LibraryManagementSystem.DAL;
using LibraryManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryManagementSystem.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly AppDbContext _db;
        public AuthorsController(AppDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            List<Author> authorList = await _db.Authors.ToListAsync();
            return View(authorList);
        }

        public async Task<IActionResult> Create()
        {
            ViewBag.Publiser= await _db.Publisers.ToListAsync();
            ViewBag.Rack= await _db.Racks.ToListAsync();
            ViewBag.Cat = await _db.Categories.ToListAsync();

            return View();      
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Author author,int publiserSelect, int rackSelect, int catSelect)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            ViewBag.Publiser = await _db.Publisers.ToListAsync();
            ViewBag.Rack = await _db.Racks.ToListAsync();
            ViewBag.Cat = await _db.Categories.ToListAsync();
            author.PubliserId = publiserSelect;
            author.RackId = rackSelect; 
            author.CategoryId= catSelect;   
            await _db.Authors.AddAsync(author);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");   
        }

        public async Task<ActionResult> Update(int? id)
        {
            ViewBag.Publiser = await _db.Publisers.ToListAsync();
            ViewBag.Rack = await _db.Racks.ToListAsync();
            ViewBag.Cat = await _db.Categories.ToListAsync();
            if (id == null)
            {
                return NotFound();
            }

            Author dbAuthor= await _db.Authors.FirstOrDefaultAsync(x=>x.Id==id);
            if(dbAuthor == null)
            {
                return BadRequest();
            }

            return View(dbAuthor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(int? id,Author author, int publiserSelect, int rackSelect, int catSelect)
        {
            ViewBag.Publiser = await _db.Publisers.ToListAsync();
            ViewBag.Rack = await _db.Racks.ToListAsync();
            ViewBag.Cat = await _db.Categories.ToListAsync();
            if (id == null)
            {
                return NotFound();
            }

            Author dbAuthor = await _db.Authors.FirstOrDefaultAsync(x => x.Id == id);
            if (dbAuthor == null)
            {
                return BadRequest();
            }
            if(!ModelState.IsValid)
            {
                return View();
            }
            dbAuthor.BookName = author.BookName;
            dbAuthor.LastName = author.LastName;
            dbAuthor.FirstName = author.FirstName;
            dbAuthor.CategoryId= catSelect;
            dbAuthor.RackId= rackSelect;
            dbAuthor.PubliserId= publiserSelect;
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Activity(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            Author dbAuthor= await _db.Authors.FirstOrDefaultAsync(x=>x.Id==id);
            if (dbAuthor == null)
            {
                return BadRequest();
            }
            if(dbAuthor.IsDeactive)
            {
                dbAuthor.IsDeactive = false;
            }
            else
            {
                dbAuthor.IsDeactive = true;
            }
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public IActionResult Search(string bookname)
        {
           List<Author> a = _db.Authors.Where(a => a.BookName.Trim().ToUpper().Contains(bookname.Trim().ToUpper())).ToList();
            if(a!=null)
            {
                return View("SearchDetail",a);

            }
            else
            {
                return NotFound("Bele bir kitab yoxdur!");  
            }

        }

        public IActionResult SearchDetail()
        {
            return View();
        }
    }
}

LibraryManagementSystem/LibraryManagementSystem/Controllers/DashboardController.cs
using LibraryManagementSystem.DAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Data;
using System.Linq;

namespace LibraryManagementSystem.Controllers
{
	public class DashboardController : Controller
	{
		private readonly AppDbContext _db;
        public DashboardController(AppDbContext db)
        {
			_db = db;
        }
        public IActionResult Index()
		{
			ViewBag.BookCount = _db.IssueBooks.Count();
			ViewBag.Rack = _db.Racks.Count();
			ViewBag.Cat = _db.Categories.Count();
			ViewBag.Pub = _db.Publisers.Count();
			return View();
		}

		
	}
}

LibraryManagementSystem/LibraryManagementSystem/Controllers/RacksController.cs
using LibraryManagementSystem.DAL;
using LibraryManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace LibraryManagementSystem.Controllers
{
    public class RacksController : Controller
    {
        private readonly AppDbContext _db;
        public RacksController(AppDbContext db)
        {
            _db = db;
        }
        public  async Task<IActionResult> Index()
        {
            List<Rack> racks = await _db.Racks.ToListAsync();
            return View(racks);
        }

        public async Task<IActionResult> Create()
        {
            return View();  
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Rack rack)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }

            bool isExist =await _db.Racks.AnyAsync(x => x.RackNumber == rack.RackNumber);
            if (isExist)
            {
                ModelState.AddModelError("RackNumber", "This rack is already exist");
                return View();
            }
           await _db.Racks.AddAsync(rack);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Update(int? id)
        {
            if(id==null)
            {
                return NotFound();
            }

            Rack dbRack=await _db.Racks.FirstOrDefaultAsync(r => r.Id==id);
            if(dbRack==null)
            {
                return BadRequest();
            }
            return View(dbRack);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, Rack rack)
        {
            if(id==null)
            {
                return NotFound();
            }

            Rack dbRack= await _db.Racks.FirstOrDefaultAsync(r=>r.Id==id);
            if(dbRack==null)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return View();
            }

            bool isExist= await _db.Racks.AnyAsync(r=>r.RackNumber==rack.RackNumber &&  r.Id!=rack.Id);
            if (isExist)
            {
                ModelState.AddModelError("RackNumber","This rack is already exist");
                return View();
            }
            dbRack.RackNumber=rack.RackNumber;
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");   
        }

        public async Task<IActionResult> Activity(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }

            Rack dbRack = await _db.Racks.FirstOrDefaultAsync(r=>r.Id==id);
            if (dbRack==null)
            {
                return BadRequest();
            }

            if(dbRack.IsDecative)
            {
                dbRack.IsDecative = false;
            }
            else
            {
                dbRack.IsDecative = true;
            }
           await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

LibraryManagementSystem/LibraryManagementSystem/Controllers/UsersController.cs
using LibraryManagementSystem.Models;
using LibraryManagementSystem.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryManagementSystem.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        public UsersController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;    
        }
        public async Task<IActionResult> Index()
        {
            List<AppUser> appUsers = await _userManager.Users.ToListAsync();
            List<UserVM> userVMs = new List<UserVM>();
            foreach (AppUser user in appUsers)
            {
                UserVM userVM = new UserVM
                {
                    Id = user.Id,
                    FullName = user.Name + user.Surname,
                    Username= user.UserName,    
                    Email = user.Email,
                    IsDeactive = user.IsDeactive,
                    Role = (await _userManager.GetRolesAsync(user)).FirstOrDefault()
                };
                userVMs.Add(userVM);
            }

            return View(userVMs);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(RegisterVM registerVM, string roleName)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }
            AppUser appUser = new AppUser
            {
                Name= registerVM.Name,
                Surname= registerVM.Surname,
                Email= registerVM.Email,
                UserName=registerVM.Username
            };

           IdentityResult identityResult= await _userManager.CreateAsync(appUser);
            if (!identityResult.Succeeded)
            {
                foreach (IdentityError error in identityResult.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return View();
            }

            await _userManager.AddToRoleAsync(appUser, roleName);   
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Update(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

           
            AppUser appUser= await _userManager.FindByIdAsync(id);  
            if (appUser == null)
            {
                return BadRequest();
            }
           
            UpdateVM updateVM = new UpdateVM()
            {
              Email=appUser.Email,
              Username=appUser.UserName,
              Name=appUser.Name,
              Surname= appUser.Surname,
              Role = (await _userManager.GetRolesAsync(appUser)).First()
            };

            return View(updateVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(string id,UpdateVM updateVM, string roleName)
        {
            if (id == null)
            {
                return NotFound();
            }
             AppUser appUser = await _userManager.FindByIdAsync(id);
            if (appUser == null)
            {
                return BadRequest();
            }

            string oldRole = (await _userManager.GetRolesAsync(appUser)).First();

            UpdateVM dbUpdateVM = new UpdateVM()
            {
                Email = appUser.Email,
                Username = appUser.UserName,
                Name = appUser.Name,
                Surname = appUser.Surname,
                Role = oldRole
            };
            appUser.Surname = updateVM.Surname;
            appUser.Name = updateVM.Name;
            appUser.UserName = updateVM.Username;
            appUser.Email = updateVM.Email;

         IdentityResult redidentityResult= await _userManager.RemoveFromRoleAsync(appUser,roleName);
            if (!redidentityResult.Succeeded)
            {
                foreach (IdentityError error in redidentityResult.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return View();
            }
         IdentityResult adddidentityResult= await _userManager.AddToRoleAsync(appUser,roleName);
            if (!adddidentityResult.Succeeded)
            {
                foreach (IdentityError error in adddidentityResult.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return View();
            }
            await _userManager.UpdateAsync(appUser);
            return RedirectToAction("Index");
        }
          public async Task<IActionResult> Activity(string id)
        {
            if(id == null)
            {
                return NotFound();
            }

            AppUser appUser= await _userManager.FindByIdAsync(id);  
            if (appUser == null)
            {
                return BadRequest();
            }
            if(appUser.IsDeactive)
            {
                appUser.IsDeactive = false;
            }
            else
            {
                appUser.IsDeactive = true;
            }
            await _userManager.UpdateAsync(appUser);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ResetPassword(string id)
        {
            if(id == null)
            {
                return NotFound();
            }
            AppUser appUser = await _userManager.FindByIdAsync(id);
            if (appUser == null)
            {
                return BadRequest();
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ResetPassword(string id, ResetPasswordVM reset)
        {
            if (id == null)
            {
                return NotFound();
            }
            AppUser appUser = await _userManager.FindByIdAsync(id);
            if (appUser == null)
            {
                return BadRequest();
            }
         string token= await _userManager.GeneratePasswordResetTokenAsync(appUser);
           IdentityResult ıdentityResult= await _userManager.ResetPasswordAsync(appUser,token,reset.Password);
            if (!ıdentityResult.Succeeded)
            {
                foreach (IdentityError error in ıdentityResult.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return View();
            }
            return RedirectToAction("Index");
        }



    }
}

LibraryManagementSystem/LibraryManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Library Management System</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js"></script>

    <link href="~/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
</head>

<body>
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-light navbar-light">
                <a href="index.html" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary"><i class="fa fa-hashtag me-2"></i>LibraryMS</h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="~/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <span>@User.Identity.Name</span>
                            }
                        </h6>
                        <span>
                           @if(User.IsInRole("Admin"))
                           {
                               <div>Admin</div>
                           }
                        </span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a asp-action="Index" asp-controller="Dashboard" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                   
                   
                    <a asp-action="Index" asp-controller="Home" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-book"></i> Book Management</a>
                    <a asp-action="Index" asp-controller="Categories" class="dropdown-item"><i class="fa-solid fa-check"></i> Category</a>
                    <a asp-action="Index" asp-controller="Authors" class="dropdown-item"><i class="fa-solid fa-check"></i> Authors</a>
                    <a asp-action="Index" asp-controller="Publisers" class="dropdown-item"><i class="fa-solid fa-check"></i> Publisers</a>
                    <a asp-action="Index" asp-controller="Racks" class="dropdown-item"><i class="fa-solid fa-check"></i> Racks</a>
                           
                     
                    
                    <a asp-action="Index" asp-controller="IssueBook" class="nav-item nav-link "><i class="fa fa-chart-bar me-2"></i> Issue Book</a>
                    <a asp-action="Index" asp-controller="Users" class="nav-item nav-link "><i class="fa-solid fa-user"></i> Users</a>
                    <a asp-action="Logout"asp-controller="Account" class="nav-item nav-link "><i class="fa-solid fa-right-from-bracket"></i> LogOut</a>

                    

                </div>
            </nav>
        </div>
        <!-- Sidebar End -->
        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                <form action="/Authors/Search" method="get" class="d-none d-md-flex ms-4">
                    <input name="bookname" href="textbox" class="form-control border-0" type="search" placeholder="Search">
                </form>
                <div class="navbar-nav align-items-center ms-auto">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-envelope me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex">Message</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="~/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="~/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="~/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all message</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-bell me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex">Notificatin</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Profile updated</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">New user added</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Password changed</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all notifications</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img class="rounded-circle me-lg-2" src="~/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                            <span class="d-none d-lg-inline-flex">
                                 @if (User.Identity.IsAuthenticated)
                                 {
                                        <span>@User.Identity.Name</span>
                                  }
                               
                            </span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a asp-action="Login" asp-controller="Account"  class="dropdown-item">Login</a>
                            <a asp-action="Register" asp-controller="Account" class="dropdown-item">Register</a>
                            <a asp-action="Logout" asp-controller="Account" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->
          

             @RenderBody()
           
            <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4" style="margin-top:800px">
                <div class="bg-light rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            &copy; <a href="#">Your Site Name</a>, All Right Reserved.
                        </div>
                         <div class="col-12 col-sm-6 text-center text-sm-end">
                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            Designed By <a href="https://htmlcodex.com">HTML Codex</a>
                            </br>
                            Distributed By <a class="border-bottom" href="https://themewagon.com" target="_blank">ThemeWagon</a>
                        </div> 
                    </div>
                </div>
            </div> 
            <!-- Footer End -->
        </div>
        <!-- Content End -->
        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/chart/chart.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>
    @section Scripts{
        <partial name="_ValidationScriptsPartial" />
    }
</body>

</html>